name: build
on:
    push:
        tags:
            - 'v*'
env:
    PLUGIN_NAME: EdgeWorkspaces
    PLUGIN_VERSION: ${{ github.event.ref }}

jobs:
    build:
        strategy:
            matrix:
                platform: [x64] # TODO: add ARM64
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
           
            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: 8.0.x
           
            - name: Build
              run: dotnet build Community.PowerToys.Run.Plugin.EdgeWorkspaces.sln --configuration Release /p:Platform=${{matrix.platform}} /p:EnableWindowsTargeting=true
           
            - name: Prepare artifact
              run: |
                Remove-Item -Path bin/* -Recurse -Include *.xml, *.pdb, PowerToys.*, Wox.*
                Rename-Item -Path bin/${{matrix.platform}}/Release -NewName $env:PLUGIN_NAME
           
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: ${{env.PLUGIN_NAME}}-${{env.PLUGIN_VERSION}}-${{matrix.platform}}
                path: Community.PowerToys.Run.Plugin.EdgeWorkspaces/bin/${{matrix.platform}}/*
